{
 "title": "Node monitoring - Mandragora",
 "description": "Dashboard for Story Protocol.",
 "tags": [ "Blockchain" ],
 "time": { "from": "2024-10-20T08:36:19.320Z", "to": "2024-10-20T08:40:46.489Z" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "chain_id", "label": "Chain ID", "query": "iliad-0" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({chain_id=\"$chain_id\"},instance)"
    }
   },
   {
    "name": "validator",
    "query": "E3F9285F998C8554FCE49E00CC16BCEF39097928"
   },
   {
    "name": "copy_of_validator",
    "query": "E3F9285F998C8554FCE49E00CC16BCEF39097928"
   }
  ]
 },
 "panels": [
  {
   "title": "Missing validators",
   "type": "timeseries",
   "description": "Missing validator in the current block height",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "% of prevote",
   "type": "timeseries",
   "description": "% of prevote on latest block heights",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent{chain_id=\"$chain_id\",vote_type=\"prevote\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Validator VP",
   "type": "stat",
   "description": "Total voting power of the validator within the consensus set",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{chain_id=\"$chain_id\", validator_address=\"E3F9285F998C8554FCE49E00CC16BCEF39097928\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{chain_id=\"$chain_id\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "% of precommit",
   "type": "timeseries",
   "description": "% of precommit on latest block height",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent{chain_id=\"$chain_id\",vote_type=\"precommit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Network Input",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_recheck_times{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_send_bytes_total{chain_id=\"$chain_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}